/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import logic.Constant;
import logic.FOLBCΑsk;
import logic.Relation;
import logic.Term;
import logic.Variable;
import parser.PrologParser;

/**
 *
 * @author tsipiripo
 */
public class MainWindow extends javax.swing.JFrame
{

    File choosedFile;
    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        promptTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        loadButton = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        promptTextArea.setColumns(20);
        promptTextArea.setRows(5);
        jScrollPane1.setViewportView(promptTextArea);

        loadButton.setText("Load");
        loadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(loadButton);

        jMenu2.setText("Run");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_loadButtonMouseClicked
    {//GEN-HEADEREND:event_loadButtonMouseClicked
        System.out.print("clicked");
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("C:\\Users\\tsipiripo\\Google Drive\\sxoli\\5o eksamino\\texnith\\15-16\\shared\\assignment2"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "myProlog", "pro");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           
            choosedFile = chooser.getSelectedFile();
            PrologParser.parseFile(choosedFile);
             System.out.println(choosedFile.getAbsolutePath());
        }
        
        
    }//GEN-LAST:event_loadButtonMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Relation query = new Relation("father_child");
       // Variable var1 = new Variable("tom");
        //Variable var2 = new Variable("sally");
        Constant c1=new Constant("tom");
        Constant c2=new Constant("sally");
        query.addArgument(c1);
        query.addArgument(c2);
        
        FOLBCΑsk fol = new FOLBCΑsk();
        
        ArrayList<HashMap<Variable, Term>> answers = fol.ask(interprol.InterProl.kb, query);
        
        for (HashMap<Variable, Term> answer : answers) 
        {
            System.out.println(answer.toString());
            
        }
        
        System.out.println("End");
    }//GEN-LAST:event_jMenu2MouseClicked

    public static void printlnToPrompt(String message)
    {
        promptTextArea.append(message+"\n");
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu loadButton;
    private static javax.swing.JTextArea promptTextArea;
    // End of variables declaration//GEN-END:variables
}
